tor-address:
  name: Network Tor Address
  description: The Tor address for the network interface. 
  type: pointer
  subtype: package
  package-id: mempool
  target: tor-address
  interface: main
bitcoind:
  type: union
  name: Bitcoin Core
  description: The Bitcoin Core node to connect to
  tag:
    id: type
    name: Type
    description: |
      - Internal: The Bitcoin Core service installed to your Embassy
      - Internal Proxy: The Bitcoin Proxy service installed on your Embassy
      - External: A Bitcoin Core node running on a different device
    variant-names:
      internal: Internal
      internal-proxy: Internal (Bitcoin Proxy)
      external: External
  default: internal
  variants:
    internal:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.username"
        multi: false
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user for Bitcoin Core
        subtype: package
        package-id: bitcoind
        target: config
        selector: "$.rpc.password"
        multi: false
    internal-proxy:
      user:
        type: pointer
        name: RPC Username
        description: The username for the RPC user allocated to Mempool
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "mempool")].name'
      password:
        type: pointer
        name: RPC Password
        description: The password for the RPC user allocated to Mempool
        subtype: package
        package-id: btc-rpc-proxy
        target: config
        multi: false
        selector: '$.users.[?(@.name == "mempool")].password'
    external:
      host:
        type: string
        name: Public Address
        description: The public address of your Bitcoin Core RPC server
        nullable: false
      user:
        type: string
        name: RPC Username
        description: The username for the RPC user on your Bitcoin Core RPC server
        nullable: false
      password:
        type: string
        name: RPC Password
        description: The password for the RPC user on your Bitcoin Core RPC server
        nullable: false

