tor-address:
  name: Network Tor Address
  description: The Tor address for the network interface. 
  type: pointer
  subtype: package
  package-id: mempool
  target: tor-address
  interface: main
lan-address:
  name: Network LAN Address
  description: The LAN address for the network interface. 
  type: pointer
  subtype: package
  package-id: mempool
  target: lan-address
  interface: main
bitcoin:
  type: object
  name: Bitcoin Core RPC
  description: The Bitcoin Core node to connect to over the RPC interface
  nullable: false
  spec:
    bitcoind-rpc:
      type: union
      name: Bitcoin Core RPC
      description: The Bitcoin Core node to connect to over the RPC interface
      tag:
        id: type
        name: Type
        variant-names:
          internal: Internal
          external: External
        description: |
          The Bitcoin Core node to connect to:
            - internal: The Bitcoin Core and Proxy services installed to your Embassy
            - external: An unpruned Bitcoin Core node running on a different device
      default: internal
      variants:
        internal:
          rpc-user:
            type: pointer
            name: RPC Username
            description: The username for the RPC user allocated to Mempool
            subtype: package
            package-id: btc-rpc-proxy
            target: config
            multi: false
            selector: '$.users.[?(@.name == "mempool")].name'
          rpc-password:
            type: pointer
            name: RPC Password
            description: The password for the RPC user allocated to Mempool
            subtype: package
            package-id: btc-rpc-proxy
            target: config
            multi: false
            selector: '$.users.[?(@.name == "mempool")].password'
        external:
          connection-settings:
            type: union
            name: Connection Settings
            description: Information to connect to an external unpruned Bitcoin Core node
            tag:
              id: type
              name: Type
              description: |
                - Manual: Raw information for finding a Bitcoin Core node
                - Quick Connect: A Quick Connect URL for a Bitcoin Core node
              variant-names:
                manual: Manual
                quick-connect: Quick Connect
            default: quick-connect
            variants:
              manual:
                rpc-host:
                  type: string
                  name: Public Address
                  description: The public address of your Bitcoin Core server
                  nullable: false
                rpc-user:
                  type: string
                  name: RPC Username
                  description: The username for the RPC user on your Bitcoin Core RPC server
                  nullable: false
                rpc-password:
                  type: string
                  name: RPC Password
                  description: The password for the RPC user on your Bitcoin Core RPC server
                  nullable: false
                rpc-port:
                  type: number
                  name: RPC Port
                  description: The port that your Bitcoin Core RPC server is bound to
                  nullable: false
                  range: "[0,65535]"
                  integral: true
                  default: 8332
              quick-connect:
                quick-connect-url:
                  type: string
                  name: Quick Connect URL
                  description: |
                    The Quick Connect URL for your Bitcoin Core RPC server
                    NOTE: LND will not accept a .onion url for this option
                  nullable: false
                  pattern: 'btcstandup://[^:]*:[^@]*@[a-zA-Z0-9.-]+:[0-9]+(/(\?(label=.+)?)?)?'
                  patternDescription: Must be a valid Quick Connect URL. For help, check out https://github.com/BlockchainCommons/Gordian/blob/master/Docs/Quick-Connect-API.md